--1.
ALTER TABLE RESULTATS
ADD CONSTRAINT CK_NOTE_RANGE CHECK (POINTS >= 0 AND POINTS <= 20);

--2.
ALTER TABLE ELEVES
ADD CONSTRAINT check_sexe CHECK (SEXE IN ('m', 'M', 'f', 'F') OR SEXE IS NULL);

--3.
SELECT *
FROM PROFESSEURS
WHERE SALAIRE_ACTUEL > SALAIRE_BASE;

--4.
ALTER TABLE PROFESSEURS
ADD CONSTRAINT check_salaire_base_actuel CHECK (SALAIRE_BASE < SALAIRE_ACTUEL);

--5.
CREATE FUNCTION dbo.DoubleMoyenneSalaire(@specialite VARCHAR(20)) RETURNS INT
AS
BEGIN
    DECLARE @doubleMoyenne INT;
    SELECT @doubleMoyenne = 2 * AVG(SALAIRE_ACTUEL)
    FROM PROFESSEURS
    WHERE SPECIALITE = @specialite;

    RETURN @doubleMoyenne;
END;


